name: intro_debug_profile
channels:
  - defaults
dependencies:
  - openssl
  - pip=20.3.3
  - python=3.8.5
  - setuptools
  - sqlite
  - wheel
  - zlib
  - pip:
    - atomicwrites
    - attrs
    - colorama
    - guppy3
    - iniconfig
    - memory-profiler
    - numpy
    - packaging
    - pandas
    - pluggy
    - psutil
    - py
    - pyparsing
    - pytest==6.2.1
    - python-dateutil
    - pytz
    - six
    - toml
    - pdbpp
    - line_profiler 
